name: frontend_backend_test
version: '1.0'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
#      - ./backend/config/config.yaml:/app/config.yaml  # you can use something like this to change the config file
      - ./vgrdl_r2b1_bs2022_0.xlsx:/vgrdl_r2b1_bs2022_0.xlsx
